package com.bookstore.model;
// Generated Oct 10, 2023, 5:06:29 PM by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Discounts generated by hbm2java
 */
@Entity
@Table(name = "Discounts", schema = "dbo", catalog = "bookstore", uniqueConstraints = @UniqueConstraint(columnNames = "book_id"))
public class Discounts implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer discountId;
	private Books books;
	private double discountPercentage;
	private boolean active;
	private Date startedDate;
	private Date endedDate;
	private String discountCode;
	private Set<OrderDetails> orderDetailses = new HashSet<OrderDetails>(0);

	public Discounts() {
	}

	public Discounts(double discountPercentage, boolean active, Date startedDate, Date endedDate) {
		this.discountPercentage = discountPercentage;
		this.active = active;
		this.startedDate = startedDate;
		this.endedDate = endedDate;
	}

	public Discounts(Books books, double discountPercentage, boolean active, Date startedDate, Date endedDate,
			String discountCode, Set<OrderDetails> orderDetailses) {
		this.books = books;
		this.discountPercentage = discountPercentage;
		this.active = active;
		this.startedDate = startedDate;
		this.endedDate = endedDate;
		this.discountCode = discountCode;
		this.orderDetailses = orderDetailses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "discount_id", unique = true, nullable = false)
	public Integer getDiscountId() {
		return this.discountId;
	}

	public void setDiscountId(Integer discountId) {
		this.discountId = discountId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "book_id", unique = true)
	public Books getBooks() {
		return this.books;
	}

	public void setBooks(Books books) {
		this.books = books;
	}

	@Column(name = "discount_percentage", nullable = false, precision = 53, scale = 0)
	public double getDiscountPercentage() {
		return this.discountPercentage;
	}

	public void setDiscountPercentage(double discountPercentage) {
		this.discountPercentage = discountPercentage;
	}

	@Column(name = "active", nullable = false)
	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "started_date", nullable = false, length = 23)
	public Date getStartedDate() {
		return this.startedDate;
	}

	public void setStartedDate(Date startedDate) {
		this.startedDate = startedDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ended_date", nullable = false, length = 23)
	public Date getEndedDate() {
		return this.endedDate;
	}

	public void setEndedDate(Date endedDate) {
		this.endedDate = endedDate;
	}

	@Column(name = "discount_code")
	public String getDiscountCode() {
		return this.discountCode;
	}

	public void setDiscountCode(String discountCode) {
		this.discountCode = discountCode;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "discounts")
	public Set<OrderDetails> getOrderDetailses() {
		return this.orderDetailses;
	}

	public void setOrderDetailses(Set<OrderDetails> orderDetailses) {
		this.orderDetailses = orderDetailses;
	}

}
