package com.bookstore.model;
// Generated Oct 10, 2023, 5:06:29 PM by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import java.util.Base64;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * ReviewImages generated by hbm2java
 */
@Entity
@Table(name = "ReviewImages", schema = "dbo", catalog = "bookstore")
public class ReviewImages implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private Integer imageId;
	private Reviews reviews;
	private byte [] reviewImg;
	private String base64Image;
	
	public ReviewImages() {
	}

	public ReviewImages(Reviews reviews, byte [] reviewImg) {
		this.reviews = reviews;
		this.reviewImg = reviewImg;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "image_id", unique = true, nullable = false)
	public Integer getImageId() {
		return this.imageId;
	}

	public void setImageId(Integer imageId) {
		this.imageId = imageId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "review_id", nullable = false)
	public Reviews getReviews() {
		return this.reviews;
	}

	public void setReviews(Reviews reviews) {
		this.reviews = reviews;
	}

	@Column(name = "review_img", nullable = false)
	public byte [] getReviewImg() {
		return this.reviewImg;
	}

	public void setReviewImg(byte [] reviewImg) {
		this.reviewImg = reviewImg;
	}

	@Transient
	public String getBase64Image() {
		this.base64Image = Base64.getEncoder().encodeToString(this.reviewImg);
		return this.base64Image;
	}
	
	@Transient
	public void setBase64Image(String base64Image) {
		this.base64Image = base64Image;
	}
	
}
