package com.bookstore.model;
// Generated Oct 10, 2023, 5:06:29 PM by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Shipping generated by hbm2java
 */
@Entity
@Table(name = "Shipping", schema = "dbo", catalog = "bookstore", uniqueConstraints = @UniqueConstraint(columnNames = "tracking_number"))
@NamedQueries({ @NamedQuery(name = "Shipping.findAll", query = "SELECT s FROM Shipping s ORDER BY s.shippingId")
	})
public class Shipping implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer shippingId;
	private TransportUnit transportUnit;
	private UserAddress userAddress;
	private Date startDate;
	private Date expectedDate;
	private Date endDate;
	private String deliveryStatus;
	private String trackingNumber;
	private Set<Orders> orderses = new HashSet<Orders>(0);

	public Shipping() {
	}

	public Shipping(TransportUnit transportUnit, UserAddress userAddress, Date startDate, Date expectedDate,
			Date endDate, String deliveryStatus, String trackingNumber) {
		this.transportUnit = transportUnit;
		this.userAddress = userAddress;
		this.startDate = startDate;
		this.expectedDate = expectedDate;
		this.endDate = endDate;
		this.deliveryStatus = deliveryStatus;
		this.trackingNumber = trackingNumber;
	}

	public Shipping(TransportUnit transportUnit, UserAddress userAddress, Date startDate, Date expectedDate,
			Date endDate, String deliveryStatus, String trackingNumber, Set<Orders> orderses) {
		this.transportUnit = transportUnit;
		this.userAddress = userAddress;
		this.startDate = startDate;
		this.expectedDate = expectedDate;
		this.endDate = endDate;
		this.deliveryStatus = deliveryStatus;
		this.trackingNumber = trackingNumber;
		this.orderses = orderses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "shipping_id", unique = true, nullable = false)
	public Integer getShippingId() {
		return this.shippingId;
	}

	public void setShippingId(Integer shippingId) {
		this.shippingId = shippingId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "unit_id", nullable = false)
	public TransportUnit getTransportUnit() {
		return this.transportUnit;
	}

	public void setTransportUnit(TransportUnit transportUnit) {
		this.transportUnit = transportUnit;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "address_id", nullable = false)
	public UserAddress getUserAddress() {
		return this.userAddress;
	}

	public void setUserAddress(UserAddress userAddress) {
		this.userAddress = userAddress;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "start_date", nullable = false, length = 23)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "expected_date", nullable = false, length = 23)
	public Date getExpectedDate() {
		return this.expectedDate;
	}

	public void setExpectedDate(Date expectedDate) {
		this.expectedDate = expectedDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "end_date",length = 23)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "delivery_status", nullable = false)
	public String getDeliveryStatus() {
		return this.deliveryStatus;
	}

	public void setDeliveryStatus(String deliveryStatus) {
		this.deliveryStatus = deliveryStatus;
	}

	@Column(name = "tracking_number", unique = true, nullable = false)
	public String getTrackingNumber() {
		return this.trackingNumber;
	}

	public void setTrackingNumber(String trackingNumber) {
		this.trackingNumber = trackingNumber;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "shipping")
	public Set<Orders> getOrderses() {
		return this.orderses;
	}

	public void setOrderses(Set<Orders> orderses) {
		this.orderses = orderses;
	}

}