package com.bookstore.model;
// Generated Oct 31, 2023, 7:05:03 PM by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * TransportUnit generated by hbm2java
 */
@Entity
@Table(name = "TransportUnit", schema = "dbo", catalog = "bookstore", uniqueConstraints = @UniqueConstraint(columnNames = "tracking_number"))
@NamedQueries({ @NamedQuery(name = "TransportUnit.findAll", query = "SELECT t FROM TransportUnit t ORDER BY t.unitId"),
	@NamedQuery(name = "TransportUnit.findByUnitName", query = "SELECT t FROM TransportUnit t WHERE t.name = :name")
	})
public class TransportUnit implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer unitId;
	private String name;
	private String type;
	private double price;
	private Integer fastShipping;
	private Integer slowShipping;
	private Date createdAt;
	private Date modifiedAt;
	private String trackingNumber;
	private Set<Shipping> shippings = new HashSet<Shipping>(0);

	public TransportUnit() {
	}

	public TransportUnit(String name, double price, Date createdAt, Date modifiedAt,
			String trackingNumber) {
		this.name = name;
		this.price = price;
		this.createdAt = createdAt;
		this.modifiedAt = modifiedAt;
		this.trackingNumber = trackingNumber;
	}

	public TransportUnit(String name, String type, double price, Integer fastShipping, Integer slowShipping,
			Date createdAt, Date modifiedAt, String trackingNumber, Set<Shipping> shippings) {
		this.name = name;
		this.type = type;
		this.price = price;
		this.fastShipping = fastShipping;
		this.slowShipping = slowShipping;
		this.createdAt = createdAt;
		this.modifiedAt = modifiedAt;
		this.trackingNumber = trackingNumber;
		this.shippings = shippings;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "unit_id", unique = true, nullable = false)
	public Integer getUnitId() {
		return this.unitId;
	}

	public void setUnitId(Integer unitId) {
		this.unitId = unitId;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "type")
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "price", nullable = false, precision = 53, scale = 0)
	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	@Column(name = "fast_shipping")
	public Integer getFastShipping() {
		return this.fastShipping;
	}

	public void setFastShipping(Integer fastShipping) {
		this.fastShipping = fastShipping;
	}

	@Column(name = "slow_shipping")
	public Integer getSlowShipping() {
		return this.slowShipping;
	}

	public void setSlowShipping(Integer slowShipping) {
		this.slowShipping = slowShipping;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 23)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modified_at", nullable = false, length = 23)
	public Date getModifiedAt() {
		return this.modifiedAt;
	}

	public void setModifiedAt(Date modifiedAt) {
		this.modifiedAt = modifiedAt;
	}

	@Column(name = "tracking_number", unique = true, nullable = false)
	public String getTrackingNumber() {
		return this.trackingNumber;
	}

	public void setTrackingNumber(String trackingNumber) {
		this.trackingNumber = trackingNumber;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "transportUnit")
	public Set<Shipping> getShippings() {
		return this.shippings;
	}

	public void setShippings(Set<Shipping> shippings) {
		this.shippings = shippings;
	}

}
