package com.bookstore.model;
// Generated Oct 31, 2023, 8:46:54 AM by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * Warehouse generated by hbm2java
 */
@Entity
@Table(name = "Warehouse", schema = "dbo", catalog = "bookstore")
@NamedQueries({ @NamedQuery(name = "Warehouse.findAll", query = "SELECT wh FROM Warehouse wh ORDER BY wh.warehouseId"),
		@NamedQuery(name = "Warehouse.countAll", query = "SELECT COUNT(wh) FROM Warehouse wh"),
		@NamedQuery(name = "Warehouse.findItem", query = "SELECT wh FROM Warehouse wh WHERE wh.books = :book"),
})
public class Warehouse implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer warehouseId;
	private Books books;
	private int quantityInStock;
	private int quantitySold;

	public Warehouse() {
	}

	public Warehouse(Books books, int quantityInStock, int quantitySold) {
		this.books = books;
		this.quantityInStock = quantityInStock;
		this.quantitySold = quantitySold;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "warehouse_id", unique = true, nullable = false)
	public Integer getWarehouseId() {
		return this.warehouseId;
	}

	public void setWarehouseId(Integer warehouseId) {
		this.warehouseId = warehouseId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "book_id", nullable = false)
	public Books getBooks() {
		return this.books;
	}

	public void setBooks(Books books) {
		this.books = books;
	}

	@Column(name = "quantity_in_stock", nullable = false)
	public int getQuantityInStock() {
		return this.quantityInStock;
	}

	public void setQuantityInStock(int quantityInStock) {
		this.quantityInStock = quantityInStock;
	}

	@Column(name = "quantity_sold", nullable = false)
	public int getQuantitySold() {
		return this.quantitySold;
	}

	public void setQuantitySold(int quantitySold) {
		this.quantitySold = quantitySold;
	}

}
